### ISSUE TITLE
For training on custom dataset, I saw that in your smoke.yaml example stated that object class need to +1, does that mean if my dataset got 28classes originally, then I also need to +1 classes, which make my number of classes become 29?

### ISSUE THREAD

**Issue by MheadHero** [sovit-123/fastercnn-pytorch-training-pipeline#11]
One more extra question is that does this repo require any specific dataset format? Like in the example is voc format?

**Comment by sovit-123** [comment]
Yes, it is required VOC format. It may support more formats in the future. But it is a complicated thing to handle and may require more time.
