### ISSUE TITLE
ValueError: y_max is less than or equal to y_min for bbox (tensor(0.9438), tensor(0.5500), tensor(0.9563), tensor(0.5500), tensor(26))

### ISSUE THREAD

**Issue by MheadHero** [sovit-123/fastercnn-pytorch-training-pipeline#13]
Hi, I was using the same dataset which split into train/valid/test. When I use train.py, it has no problem at all, but when I execute validate.py it comes out this error. You have any ideas about it?
![image](https://user-images.githubusercontent.com/24875124/170460805-e7506ea3-13e7-4184-a396-66275e8a2fe8.png)

**Comment by sovit-123** [comment]
Looks like dataset issue. The y_max should be larger than y_min obviously. But if you observe after normalization y_min = y_max =  0.5500. That's what is causing the error.

**Comment by MheadHero** [comment]
> Looks like dataset issue. The y_max should be larger than y_min obviously. But if you observe after normalization y_min = y_max = 0.5500. That's what is causing the error.

Problem is **I used the same dataset too in training, and training process went smooth** but then when use validate.py it outputs error like this. So I think is not dataset issue. And if you google around this issue, there are similar issue in yolov3 saying that this is problem with albumentation. So, any idea?

**Comment by MheadHero** [comment]
Please, can you help?

**Comment by sovit-123** [comment]
Is it a public dataset that I can try out.

**Comment by MheadHero** [comment]
I can share you the dataset, actually you mind add me on discord, so we can directly communicate things about object detection? (if you don't shy haha)

dataset link: !curl -L "https://app.roboflow.com/ds/LsjVvA8COo?key=UA3zJoXRny" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip

**Comment by MheadHero** [comment]
This dataset is resized into 320x320, and auto-orientation is applied.

**Comment by MheadHero** [comment]
If you don't mind, you can add my discord, so maybe we can make an international friend right. Beside that, I also can directly ask you questions regarding object detection.

**Comment by sovit-123** [comment]
Can you please check the friend request?

**Comment by MheadHero** [comment]
I have added you, and has hi to you, do you see it?
