### ISSUE TITLE
Hi, can you make a simple training.ipynb or a guideline kaggle notebook for newbies like me? (I am using roboflow to manage the dataset too)

### ISSUE THREAD

**Issue by MheadHero** [sovit-123/fastercnn-pytorch-training-pipeline#9]
I am using roboflow to manage the dataset. FYI roboflow can export a dataset to different format.

**Comment by sovit-123** [comment]
Hello @MheadHero. Sure, I will be creating both, a Kaggle notebook, and a Colab notebook and update the repo in the next 2-3 days.

**Comment by MheadHero** [comment]
Thank you sir, for dataset if can also use roboflow to export it, as this would be easier.

**Comment by sovit-123** [comment]
Sure @MheadHero . I will try to make a few different examples.

**Comment by MheadHero** [comment]
Hi, will you release any kaggle notebook today?

**Comment by sovit-123** [comment]
@MheadHero Yes. The repo will be updated today.

**Comment by MheadHero** [comment]
Thanks! you are the greatest man in the world

**Comment by sovit-123** [comment]
Thanks a lot. But really, I am just trying to do my part in the open-source machine learning world 🙂.
By the way, I have uploaded the notebook. You can find them in the [notebook_examples](https://github.com/sovit-123/fastercnn-pytorch-training-pipeline/tree/main/notebook_examples) folder.
I hope that this solves the issue. I am closing this issue for now.
